spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.106:3306/shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
 #logging:
 # pattern:
    #console: "%d - %msg%n"
 # path: /var/log/tomcat/
  # file: /var/log/tomcat/sell.log
  #level:
   # com.liwei.repository.MyTestt: info
   #level:  debug